In [1]:
import pandas as pd

df1= pd.read_csv('full_twitter_after_trollremoval.csv')

In [2]:
df1.head()

,Unnamed: 0,ID,keywords,Date,tweet_timestamp,Tweet,anger,fear,sadness,joy,valence,user_id,user_status_count,user_follower,user_friend
0,0,1.0,wuhan,01/28/20,1.580174e+09,How to get seats or a proper place to stand in...,0.529,0.498,0.475,0.219,0.354,7.219106e+08,63330.0,232.0,201.0
1,1,2.0,wuhan,01/28/20,1.580176e+09,Highest number of cases confirmed in China am...,0.410,0.572,0.459,0.307,0.520,1.243803e+08,3956.0,414.0,276.0
2,2,3.0,wuhan,01/28/20,1.580176e+09,Wuhan virus Experts warn against complacency i...,0.472,0.552,0.464,0.201,0.350,1.901388e+07,184454.0,36627.0,150.0
3,3,4.0,wuhan,01/28/20,1.580177e+09,gtSingapore confirms 5th case of Wuhan virus h...,0.392,0.572,0.468,0.271,0.434,1.020702e+18,57212.0,525.0,390.0
4,4,5.0,wuhan,01/28/20,1.580177e+09,There is fear uncertainty and resignation in W...,0.486,0.714,0.579,0.244,0.371,8.863746e+08,1304.0,3839.0,787.0

In [3]:
df1['influencer_score']=df1['user_follower']/df1['user_friend']

In [5]:
df1.tail()

,Unnamed: 0,ID,keywords,Date,tweet_timestamp,Tweet,anger,fear,sadness,joy,valence,user_id,user_status_count,user_follower,user_friend,influencer_score
434804,437139,437140.0,covid,01/01/22,1.641051e+09,Covid19 Wealthy states and pharma companies ca...,0.482,0.532,0.430,0.191,0.442,2.592465e+07,1150478.0,3844.0,4260.0,0.902347
434805,437140,437141.0,covid,01/01/22,1.641052e+09,plausibleparrot youre gonna get ghost covid no...,0.475,0.459,0.350,0.263,0.402,1.395953e+18,1999.0,243.0,332.0,0.731928
434806,437141,437142.0,nCoV,01/01/22,1.641052e+09,Long Covid erste Definition durch die WHO http...,0.444,0.475,0.370,0.197,0.366,1.219425e+18,57.0,14.0,42.0,0.333333
434807,437142,437143.0,covid,01/01/22,1.641052e+09,adambravin As much as Covid sucked it allowed ...,0.310,0.304,0.384,0.447,0.615,1.467886e+18,664.0,515.0,494.0,1.042510
434808,437143,437144.0,covid,01/01/22,1.641052e+09,Safety of mRNA COVID19 vaccines under the micr...,0.380,0.540,0.382,0.258,0.472,1.147079e+08,216126.0,732.0,166.0,4.409639

In [13]:
def det_info_status(row):
    if float((row['influencer_score'])) > 1:
        val = 0
    else:
        val = 1
    return val

In [14]:
df1["info_status_binary"] = df1.apply(det_info_status, axis=1)

In [15]:
df1.head()

,Unnamed: 0,ID,keywords,Date,tweet_timestamp,Tweet,anger,fear,sadness,joy,valence,user_id,user_status_count,user_follower,user_friend,influencer_score,info_status,info_status_binary
0,0,1.0,wuhan,01/28/20,1.580174e+09,How to get seats or a proper place to stand in...,0.529,0.498,0.475,0.219,0.354,7.219106e+08,63330.0,232.0,201.0,1.154229,info-disseminators,0
1,1,2.0,wuhan,01/28/20,1.580176e+09,Highest number of cases confirmed in China am...,0.410,0.572,0.459,0.307,0.520,1.243803e+08,3956.0,414.0,276.0,1.500000,info-disseminators,0
2,2,3.0,wuhan,01/28/20,1.580176e+09,Wuhan virus Experts warn against complacency i...,0.472,0.552,0.464,0.201,0.350,1.901388e+07,184454.0,36627.0,150.0,244.180000,info-disseminators,0
3,3,4.0,wuhan,01/28/20,1.580177e+09,gtSingapore confirms 5th case of Wuhan virus h...,0.392,0.572,0.468,0.271,0.434,1.020702e+18,57212.0,525.0,390.0,1.346154,info-disseminators,0
4,4,5.0,wuhan,01/28/20,1.580177e+09,There is fear uncertainty and resignation in W...,0.486,0.714,0.579,0.244,0.371,8.863746e+08,1304.0,3839.0,787.0,4.878018,info-disseminators,0

In [16]:
len(df1)

434809

In [50]:
df1.to_csv('twitter_data_with_influencer_tagging.csv')

In [17]:
df1_noninfluencers = df1.loc[(df1["info_status_binary"] == 1)]

In [1]:
434809-199979

234830

In [18]:
len(df1_noninfluencers)

199979

In [19]:
df1_noninfluencers.head()

,Unnamed: 0,ID,keywords,Date,tweet_timestamp,Tweet,anger,fear,sadness,joy,valence,user_id,user_status_count,user_follower,user_friend,influencer_score,info_status,info_status_binary
7,7,8.0,wuhan,01/28/20,1.580179e+09,First person with the Wuhan virus being treate...,0.483,0.530,0.450,0.251,0.408,1.150286e+18,337.0,1411.0,2011.0,0.701641,info-seeking,1
8,8,9.0,wuhan,01/28/20,1.580179e+09,We have this chat group for everyone in SG off...,0.428,0.523,0.470,0.280,0.428,2.055352e+08,35226.0,336.0,473.0,0.710359,info-seeking,1
9,9,10.0,wuhan,01/28/20,1.580180e+09,chrisvtaylor pakhead RichardBarrow Safe harbor...,0.505,0.594,0.474,0.231,0.390,1.170536e+18,489.0,13.0,221.0,0.058824,info-seeking,1
10,10,11.0,wuhan,01/28/20,1.580180e+09,After the 5th Wuhan imported case confirmed Si...,0.414,0.499,0.471,0.332,0.501,2.913063e+07,44406.0,693.0,1285.0,0.539300,info-seeking,1
13,13,14.0,wuhan,01/28/20,1.580181e+09,Coronavirus news France to airlift citizens ou...,0.534,0.680,0.549,0.182,0.323,2.271343e+08,117.0,1.0,147.0,0.006803,info-seeking,1

In [22]:
def calculate_emotion_term(row):  
    if (((row['valence'] <= 0.52) and (row['valence'] >= 0.48)) or (row['valence'] == 0)):
        val = 'no specific emotion'
    elif row['valence'] >= 0.52:
        val = 'joy' 
    elif row['valence'] <= 0.48:
        val = 'anger'
        if ((row['fear'] > row['anger']) and (row['fear'] >= row['sadness'])):
            val = 'fear'
        elif ((row['sadness']  > row['anger']) and (row['sadness']  > row['fear'])):
            val = 'sadness'
    return val


def calculate_sentiment_term(row):
    if row['valence'] <= 0.25:
        val = 'very negative'
    elif row['valence'] <= 0.48:
        val = 'negative'
    elif row['valence'] <= 0.52:
        val = 'neutral'        
    elif row['valence'] <= 0.75:
        val = 'positive'
    else:
        val = 'very positive'
    return val

#def is_singapore(row):
#    return "r/singapore" in row["url"]
def calculate_intensity_term(row):
    if row['emotion_intensity'] < 0.4:
            val = 'low'
    if row['emotion_intensity'] < 0.6:
            val = 'moderate'
    if row['emotion_intensity'] < 0.8:
            val = 'high'
    else:
        val = 'very high'
    return val

In [24]:
df1_noninfluencers['emotion'] = df1_noninfluencers.apply(calculate_emotion_term, axis=1)
df1_noninfluencers['sentiment'] = df1_noninfluencers.apply(calculate_sentiment_term, axis=1)

C:\Users\othmana\.conda\envs\testing\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\othmana\.conda\envs\testing\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [51]:
df1_noninfluencers.to_csv('twitter_noninfluencers_withemotioncat.csv')